#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# polkit agent
if [[ ! 'pidof polkit-gnome-authentication-agent-1' ]];then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Launch clipcat daemon
clipcatd &

# Launch swww (wallpaper manager)
swww-daemon &
#hyprpaper &

# Xauthority
${SCRIPTSDIR}/xauthority &

nm-applet --indicator &
