[v1]
"amp 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["amp"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-update 16.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"chess-tui 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["chess-tui"]
"cpz 2.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cpz"]
"crabz 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["crabz"]
"dua-cli 2.30.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dua"]
"eza 0.20.21 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"fd-find 10.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"ferium 4.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["ferium"]
"fum-player 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fum"]
"hyperfine 1.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"mcman 0.4.5 (git+https://github.com/ParadigmMC/mcman.git#cac69640485735cdd0ef2ccd3039fe2cbdec1f9d)" = ["mcman"]
"minesweep 6.0.54 (registry+https://github.com/rust-lang/crates.io-index)" = ["minesweep"]
"navi 2.23.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["navi"]
"neovide 0.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["neovide"]
"ouch 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["ouch"]
"oxipng 9.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["oxipng"]
"patch-crate 0.1.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-patch-crate"]
"rmz 2.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rmz"]
"rsftch 0.7.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["rsftch"]
"ruplacer 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["ruplacer"]
"speedtest-rs 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["speedtest-rs"]
"spotify_player 0.20.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["spotify_player"]
"starship 1.22.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"steam-tui 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["steam-tui"]
"termscp 0.16.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["termscp"]
"topgrade 16.0.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["topgrade"]
"tuisky 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tuisky"]
"vkfetch-rs 0.2.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["vkfetch-rs"]
"xcp 0.23.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["xcp"]
"yazi-fm 25.2.11 (registry+https://github.com/rust-lang/crates.io-index)" = ["yazi"]
"zee 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zee"]
