palette = 'catppuccin_mocha'

format = """
[░▒▓](surface1)\
[ 󰣇 ](bg:surface1 fg:blue)\
[](bg:mauve fg:surface1)\
$directory\
[](bg:surface1 fg:mauve)\
$git_branch\
$git_status\
[](bg:surface0 fg:surface1)\
$nodejs\
$rust\
$golang\
$php\
[](bg:mantle fg:surface0)\
$time\
[ ](fg:mantle)\
\n$character"""

[directory]
style = "fg:crust bg:mauve"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:surface1 fg:mauve"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:surface1 fg:mauve"
format = '[($all_status$ahead_behind)]($style)'

[nodejs]
symbol = ""
style = "bg:surface0 fg:mauve"
format = '[ $symbol ($version)]($style)'

[rust]
symbol = ""
style = "bg:surface0 fg:mauve"
format = '[ $symbol ($version)]($style)'

[golang]
symbol = ""
style = "bg:surface0 fg:mauve"
format = '[ $symbol ($version)]($style)'

[php]
symbol = ""
style = "bg:surface0 fg:mauve"
format = '[ $symbol ($version)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:mantle fg:overlay1"
format = '[   $time ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
disabled = false
symbol = ""
success_symbol = '[ ](bold fg:mauve)'
error_symbol = '[ ](bold fg:red)'
